version: "3"

services:
  app: # 컨테이너1 : app
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "db:mysqldb"
    ports:
      - "5000:5000"
    container_name: app
    depends_on:
      - db
  db: # 컨테이너 2 : db
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flask_test
    ports:
      - "3306:3306"
    container_name: db
    



